// Generated by Wrangler on Thu May 09 2024 10:37:45 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	CALLS_API: "http://localhost:8888";
	CALLS_APP_ID: "f0ea263009299383d09d44b9fad5316c";
	LIVE_STORE: DurableObjectNamespace;
}
