#:schema node_modules/wrangler/config-schema.json
name = "openai-demo"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public" }

[vars]
OPENAI_API_KEY = "<openai api key>"
OPENAI_MODEL_ENDPOINT = "https://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01"
CALLS_BASE_URL = "https://rtc.live.cloudflare.com/v1/apps"
CALLS_APP_ID = "<calls app id>"
CALLS_APP_TOKEN = "<calls app token>"
